#!/usr/bin/env bash
#
# scripts/setup.sh — interactive first-time-setup for Docker deployments.
#
# Generates a `.env` file in the current directory with:
#   - CLAUDE_OS_AUTH_TOKEN          (random 32-byte hex)
#   - CLAUDE_OS_SECRETS_PASSPHRASE  (random 32-byte hex)
#   - CLAUDE_OS_ADMIN_EMAILS        (prompted, optional but recommended)
#   - CLAUDE_OS_SESSION_PERSIST     (prompted, default 1)
#   - CLAUDE_OS_ALLOW_REGISTRATION  (prompted, default 0)
#
# Idempotent: if .env exists, asks before overwriting and preserves any
# extra keys via a backup.
#
# Usage (after `git clone` or `curl -fsSL …docker-compose.example.yml`):
#   cd /opt/claude-os
#   curl -fsSL https://raw.githubusercontent.com/yannikits/Claude-portable/main/scripts/setup.sh \
#     | bash
#
# Or, if you have the repo checked out:
#   bash scripts/setup.sh

set -euo pipefail

ENV_FILE=".env"
TMP_ENV="$(mktemp)"
trap 'rm -f "$TMP_ENV"' EXIT

# ── colour helpers ───────────────────────────────────────────────────
red()    { printf "\033[31m%s\033[0m\n" "$*"; }
green()  { printf "\033[32m%s\033[0m\n" "$*"; }
yellow() { printf "\033[33m%s\033[0m\n" "$*"; }
bold()   { printf "\033[1m%s\033[0m\n" "$*"; }
ask()    { printf "\033[36m? %s\033[0m " "$*"; }

# ── pre-flight ───────────────────────────────────────────────────────
if ! command -v openssl >/dev/null 2>&1; then
  red "openssl ist nicht installiert — bitte 'apt install openssl' nachholen."
  exit 1
fi

echo
bold "=== claude-os Erst-Einrichtung ==="
echo

if [ -f "$ENV_FILE" ]; then
  yellow ".env existiert bereits in $(pwd)/."
  ask "Überschreiben? (existierende Werte gehen verloren; .env.bak wird angelegt) [y/N]:"
  read -r reply
  case "$reply" in
    y|Y|yes|Yes|j|J|ja|Ja)
      cp "$ENV_FILE" "${ENV_FILE}.bak"
      green "  → Backup: ${ENV_FILE}.bak"
      ;;
    *)
      red "Abgebrochen. Bestehende .env bleibt unverändert."
      exit 0
      ;;
  esac
fi

# ── 1. Auth-Token + Secrets-Passphrase ───────────────────────────────
AUTH_TOKEN="$(openssl rand -hex 32)"
SECRETS_PASSPHRASE="$(openssl rand -hex 32)"
green "Auth-Token + Secrets-Passphrase generiert (32 Bytes hex je)."
echo

# ── 2. Admin-Email ───────────────────────────────────────────────────
echo
bold "Admin-Email für Multi-User Stage 2 + HTTP-Admin-API"
echo "  Diese Adresse darf nach 'claude-os users create' auf"
echo "  /api/admin/users* zugreifen. Mehrere möglich (Komma-getrennt)."
echo "  Leer lassen wenn du erstmal Stage-1 (Token-only) fahren willst."
ADMIN_EMAIL=""
while true; do
  ask "Admin-Email (z.B. yannik@example.com), leer für keine:"
  read -r raw
  if [ -z "$raw" ]; then
    yellow "  → keine Admin-Email gesetzt (Admin-HTTP-API bleibt deaktiviert)."
    break
  fi
  # Sehr permissive Validierung: enthält @ und mindestens einen Punkt rechts davon
  if echo "$raw" | grep -Eq '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}(,[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,})*$'; then
    ADMIN_EMAIL="$raw"
    green "  → $ADMIN_EMAIL"
    break
  fi
  red "  Format ungültig. Erwartet z.B. 'user@example.com' oder 'a@x.de,b@x.de'."
done

# ── 3. Session-Persistence ───────────────────────────────────────────
echo
bold "Session-Persistenz (sessions.sqlite in /data)"
echo "  Ohne wird jeder User nach Container-Restart wieder ausgeloggt."
echo "  Empfehlung für Produktion: aktivieren."
ask "Session-Persistenz aktivieren? [Y/n]:"
read -r reply
case "$reply" in
  n|N|no|No|nein|Nein) SESSION_PERSIST=0 ;;
  *)                   SESSION_PERSIST=1 ;;
esac
green "  → CLAUDE_OS_SESSION_PERSIST=$SESSION_PERSIST"

# ── 4. Self-Registration ─────────────────────────────────────────────
echo
bold "Self-Registration (POST /api/auth/register)"
red "  WARNUNG: Nur aktivieren wenn der Server hinter Cloudflare"
red "  Access, VPN oder einem trusted Network steht."
echo "  Otherwise: brute-force + account-enumeration sind trivial."
ask "Self-Registration aktivieren? [y/N]:"
read -r reply
case "$reply" in
  y|Y|yes|Yes|j|J|ja|Ja) ALLOW_REGISTRATION=1 ;;
  *)                     ALLOW_REGISTRATION=0 ;;
esac
green "  → CLAUDE_OS_ALLOW_REGISTRATION=$ALLOW_REGISTRATION"

# ── 5. .env schreiben ────────────────────────────────────────────────
{
  echo "# Generated by scripts/setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# DO NOT COMMIT THIS FILE — it contains secrets."
  echo
  echo "CLAUDE_OS_AUTH_TOKEN=$AUTH_TOKEN"
  echo "CLAUDE_OS_SECRETS_PASSPHRASE=$SECRETS_PASSPHRASE"
  if [ -n "$ADMIN_EMAIL" ]; then
    echo "CLAUDE_OS_ADMIN_EMAILS=$ADMIN_EMAIL"
  else
    echo "# CLAUDE_OS_ADMIN_EMAILS="
  fi
  echo "CLAUDE_OS_SESSION_PERSIST=$SESSION_PERSIST"
  if [ "$ALLOW_REGISTRATION" = "1" ]; then
    echo "CLAUDE_OS_ALLOW_REGISTRATION=1"
  else
    echo "# CLAUDE_OS_ALLOW_REGISTRATION=1"
  fi
  echo "# CLAUDE_OS_SKIP_DOCTOR=1   # ← nur als Notfall-Escape, sonst leer lassen"
} > "$TMP_ENV"

mv "$TMP_ENV" "$ENV_FILE"
chmod 600 "$ENV_FILE"
trap - EXIT

echo
green "$ENV_FILE geschrieben (chmod 600)."
echo
bold "=== Nächste Schritte ==="
echo "  1. docker compose pull"
echo "  2. docker compose up -d"
echo "  3. docker compose logs -f claude-os   (warten auf 'server: listening at …')"
if [ -n "$ADMIN_EMAIL" ]; then
  echo "  4. docker compose stop claude-os"
  echo "     docker compose run --rm claude-os \\"
  echo "       node /app/dist/cli/index.js users create \\"
  echo "       --email $ADMIN_EMAIL --password 'mindestens-12-zeichen-passphrase'"
  echo "     docker compose start claude-os"
  echo "  5. Browser öffnen → mit $ADMIN_EMAIL einloggen"
else
  echo "  4. Stage-1 nur: per Bearer-Token (siehe CLAUDE_OS_AUTH_TOKEN in .env)"
  echo "     Multi-User später aktivieren: setup.sh nochmal + email setzen,"
  echo "     dann 'claude-os users create' im Container ausführen."
fi
echo
yellow "Bei Fragen: docs/server-deployment.md + tasks/v1.7.1-install-anleitung.md"
